__all__: tuple[str, ...] = (
    "PLURALKIT_API_ERROR_SYSTEM_NOT_FOUND",
    "PLURALKIT_API_ERROR_SYSTEM_FRONT_HISTORY_PRIVATE",
)


PLURALKIT_API_ERROR_SYSTEM_NOT_FOUND: int = 20001
PLURALKIT_API_ERROR_SYSTEM_FRONT_HISTORY_PRIVATE: int = 30005
